module Prato
  module Internal
    class SpecificationBuilder
      type label_type = Symbol | String
      type formatter = ^(untyped) -> untyped
      type path_part = Symbol | String
      type accessor = Symbol | String | Array[path_part] | Hash[path_part, untyped]
      type aggregate_accessor = Symbol | String | Array[path_part]
      type sql_filter = ^(::ActiveRecord::Relation, Query::Filter::filter_operator, Query::Filter::value_type) -> ::ActiveRecord::Relation?
      type ruby_filter = ^(untyped, Query::Filter::filter_operator, Query::Filter::value_type) -> bool?
      type column_only_option = :display | :filter | :sort
      type query_only_option = :filter | :sort
      type loader_id = Symbol | String
      type ruby_key = Symbol | String | Numeric | bool | nil | Array[path_part] | ^(::ActiveRecord::Base) -> untyped

      attr_reader draft_columns: Array[DraftColumn]
      attr_reader ruby_loaders: Hash[loader_id, ^(Array[::ActiveRecord::Base], LazyLoaderCache) -> untyped]?

      def initialize: () -> void

      def inner_column:
        (Symbol column_id, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, accessor accessor, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (Hash[label_type, accessor] mapping, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, expression: Symbol | String, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, count: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, sum: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, avg: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, min: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void
        | (label_type label, max: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: column_only_option) -> void

      def inner_query_column:
        (Symbol column_id, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, accessor accessor, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (Hash[label_type, accessor] mapping, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, expression: Symbol | String, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, count: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, sum: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, avg: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, min: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void
        | (label_type label, max: aggregate_accessor, ?format: formatter, ?filter: sql_filter, ?only: query_only_option) -> void

      def inner_ruby_column:
        (label_type label, ?key: ruby_key, ?filter: ruby_filter) -> void
        | (label_type label, ?key: ruby_key, ?filter: ruby_filter) { (Array[::ActiveRecord::Base], LazyLoaderCache) -> untyped } -> void
        | (Hash[label_type, loader_id] mapping, ?key: ruby_key, ?filter: ruby_filter) -> void
        | (Hash[label_type, loader_id] mapping, ?key: ruby_key, ?filter: ruby_filter) { (Array[::ActiveRecord::Base], LazyLoaderCache) -> untyped } -> void
        | (label_type label, loader_id loader_id, ?key: ruby_key, ?filter: ruby_filter) -> void
        | (label_type label, loader_id loader_id, ?key: ruby_key, ?filter: ruby_filter) { (Array[::ActiveRecord::Base], LazyLoaderCache) -> untyped } -> void

      def inner_section: (Symbol | String id) { () -> void } -> void
      def inner_ruby_loader: (loader_id id) { (Array[::ActiveRecord::Base], LazyLoaderCache) -> untyped } -> void
      def inner_config: (Configuration config) -> void
      def build: (singleton(::ActiveRecord::Base) base_model) -> Specification
    end

    class DraftColumn
      type path_part = Symbol | String
      type accessor = path_part | Array[path_part]

      attr_reader override_name: path_part?
      attr_reader accessor_name: accessor?
      attr_reader column: Specification::column_type
      attr_reader only: Configuration::default_only?
      attr_reader query_only: bool
      attr_reader output_paths: Array[path_part]

      def initialize: (path_part? override_name, accessor? accessor_name, Specification::column_type column, ?only: Configuration::default_only?, ?query_only: bool, ?output_paths: Array[path_part]) -> void
      def name: () -> accessor?
    end

    class SectionBuilder
      attr_reader spec: SpecificationBuilder

      def initialize: () -> void
      def column: (*untyped args, **untyped kwargs) -> SectionBuilder
      def ruby_column: (*untyped args, **untyped kwargs) -> SectionBuilder
      def section: (Symbol | String id) { () -> void } -> SectionBuilder
    end
  end
end
