module Prato
  class Configuration
    type key_transformation = :camelCase | :snake_case | :none
    type invalid_input = :empty | :raise
    type queryable = :all | :none | :filter | :sort

    interface _ParameterParser
      def parse_parameters: (Hash[Symbol | String, untyped] input, ^(Array[String]) -> Symbol? field_lookup) -> Query::Parameters
    end

    def self.config: () -> Configuration
    def self.configure: () ?{ (Configuration) -> void } -> Configuration
    def self.with_settings: (
      ?Configuration? base,
      ?key_transformation: key_transformation?,
      ?on_invalid_input: invalid_input?,
      ?parameter_parser: _ParameterParser?,
      ?default_page_size: Integer?,
      ?maximum_page_size: Integer?,
      ?default_queryable: queryable?,
      ?default_ruby_column_queryable: queryable?
    ) -> Configuration

    attr_accessor default_page_size: Integer
    attr_accessor maximum_page_size: Integer
    attr_accessor key_transformation: key_transformation
    attr_accessor on_invalid_input: invalid_input
    attr_accessor parameter_parser: _ParameterParser
    attr_accessor default_queryable: queryable
    attr_accessor default_ruby_column_queryable: queryable

    def initialize: () -> void
    def default_queryable=: (queryable value) -> queryable
    def default_ruby_column_queryable=: (queryable value) -> queryable
  end
end
