module Prato
  class TableBuilder
    type label_type = Symbol | String
    type formatter = ^(untyped) -> untyped
    type column_only_option = :display | :filter | :sort
    type agg_arg = Array[Symbol]

    attr_reader spec: Internal::SpecificationBuilder

    def initialize: () -> void

    def column:
      (Symbol column_id, ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, Symbol | Array[Symbol] accessor, ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, expression: Symbol | String, ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, count: Symbol | Array[Symbol], ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, sum: Array[Symbol], ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, avg: Array[Symbol], ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, min: Array[Symbol], ?format: formatter, ?only: column_only_option) -> void
      | (label_type label, max: Array[Symbol], ?format: formatter, ?only: column_only_option) -> void
      | (**(Symbol | Array[Symbol] | formatter)) -> void

    def query_column:
      (Symbol column_id, ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, Symbol | Array[Symbol] accessor, ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, expression: Symbol | String, ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, count: Symbol | Array[Symbol], ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, sum: agg_arg, ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, avg: agg_arg, ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, min: agg_arg, ?format: formatter, ?only: :filter | :sort) -> void
      | (label_type label, max: agg_arg, ?format: formatter, ?only: :filter | :sort) -> void
      | (**(Symbol | Array[Symbol] | formatter)) -> void

    def ruby_column:
      (Symbol | String loader_label, ?key: Symbol) -> void
      | (Symbol | String label, Symbol loader_id, ?key: Symbol) -> void
      | (**Symbol) -> void

    def section: (Symbol | String id) { () -> void } -> void
    def ruby_loader: (Symbol id) { (Array[ActiveRecord::Base] records, Hash[Symbol, untyped] loaded_data) -> untyped } -> void
    def configure: (
      ?Configuration? config,
      ?key_transformation: Configuration::key_transformation?,
      ?on_invalid_input: (:empty | :raise)?,
      ?parameter_parser: Configuration::_ParameterParser?,
      ?default_page_size: Integer?,
      ?maximum_page_size: Integer?,
      ?default_only: (:display | :filter | :sort)?,
      ?default_ruby_column_only: (:display | :filter | :sort)?
    ) -> void
  end
end
