module Prato
  module Types
    class Column
      attr_reader arel_node: Arel::Nodes::Node
      attr_reader format: Proc?

      @accessor: Symbol | Array[Symbol]
      @sql_alias: String

      def initialize: (Symbol | Array[Symbol] accessor, ?format: Proc?) -> void
      def resolve_arel!: (singleton(::ActiveRecord::Base) base_model, Symbol | Array[Symbol] display_id) -> void
      def extract_value: (::ActiveRecord::Base record, untyped _) -> untyped
    end
  end
end
