module Prato
  module Types
    class RubyColumn
      @loader: Symbol
      @key: Symbol | Array[Symbol]

      def initialize: (loader: Symbol, ?key: Symbol | Array[Symbol]) -> void
    end
  end
end
