module Prato
  module Types
    class RubyColumn
      @loader: Symbol
      @key: Symbol | Array[Symbol]

      def initialize: (Symbol loader, ?key: Symbol | Array[Symbol]) -> void
    end
  end
end
