module Prato
  module Query
    class Filter
      type filter_operator = :eq | :not_eq
        | :lt | :lte | :gt | :gte
        | :present | :not_present
        | :in | :not_in
        | :contains | :not_contains
        | :between | :not_between
        | :between_exclusive | :not_between_exclusive
      type scalar_value = nil | bool | Numeric | String | Symbol
      type value_type = scalar_value | Array[scalar_value]

      attr_reader field: Symbol?
      attr_reader operator: filter_operator
      attr_reader value: value_type

      def initialize: (Symbol? field, filter_operator operator, value_type value) -> void
    end
  end
end
