module Prato
  module Query
    class OrFilter
      type filter_node = Filter | AndFilter | OrFilter

      attr_reader filters: Array[filter_node]

      def initialize: (Array[filter_node] filters) -> void
    end
  end
end
