module Prato
  module Query
    class Parameters
      type filter_node = Filter | AndFilter | OrFilter

      attr_reader page: Integer?
      attr_reader per_page: Integer?
      attr_reader filters: Array[filter_node]?
      attr_reader sorts: Array[Sort]?
      attr_reader fields: Array[Symbol?]?

      def initialize: (?page: Integer?, ?per_page: Integer?, ?filters: Array[filter_node]?, ?sorts: Array[Sort]?, ?fields: Array[Symbol?]?) -> void
    end
  end
end
